#!/bin/bash

[ -n "$VERBOSE" ] && echo "postinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    configure)

	#
	# change permissions
	#
	DAEMON_CONF=__PREFIX__/conf/daemon.conf
	if [ -f "$DAEMON_CONF" ]; then
    		MAPR_USER=$( awk -F = '$1 == "mapr.daemon.user" { print $2 }' $DAEMON_CONF)
    		MAPR_GROUP=$( awk -F = '$1 == "mapr.daemon.group" { print $2 }' $DAEMON_CONF)
    		if [ ! -z "$MAPR_USER" ]; then
        		chown -R ${MAPR_USER} __PREFIX__/ksql/
    		fi
    		if [ ! -z "$MAPR_GROUP" ]; then
        		chgrp -R ${MAPR_GROUP} __PREFIX__/ksql/
    		fi
	fi
	
	mkdir -p "__INSTALL_3DIGIT__"/logs
	chmod 1777 "__INSTALL_3DIGIT__"/logs
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


