#!/bin/bash

[ -n "$VERBOSE" ] && echo "prerm called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    remove|upgrade|deconfigure)
   
     if [ -f  __PREFIX__/ksql/ksqlversion ]; then
        bash __PREFIX__/ksql/ksql-__VERSION_3DIGIT__/bin/ksql-server-stop
        bash __PREFIX__/ksql/ksql-__VERSION_3DIGIT__/bin/ksql-stop
     fi

     if [ -d __PREFIX__/ksql/ksql-__VERSION_3DIGIT__/logs ]; then
        rm -rf __PREFIX__/ksql/ksql-__VERSION_3DIGIT__/logs
     fi
  
    ;;  

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;  
esac    

